name: Update package versions

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update.yml
  schedule:
    # Every day at 7:35 UTC
    - cron: "35 7 * * *"
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  update:
    name: Update package versions

    runs-on: macos-26

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BREW_COMMIT_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@1e34f2e2acaa766b7efacb8c26352e6abbb023f9 # 2026.09.13.1
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: List casks in tap
        id: list-casks
        # List cask files in Casks directory, remove .rb extension, prefix with "jonahsnider/frc/", join with spaces
        run: |
          casks=$(find Casks -maxdepth 1 -name "*.rb" -type f -exec basename {} .rb \; | sed 's/^/jonahsnider\/frc\//' | tr '\n' ' ')
          echo "casks=$casks" >> "$GITHUB_OUTPUT"
      - name: List formulae in tap
        id: list-formulae
        # List formula files in Formula directory, remove .rb extension, prefix with "jonahsnider/frc/", join with spaces
        run: |
          formulae=$(find Formula -maxdepth 1 -name "*.rb" -type f -exec basename {} .rb \; | sed 's/^/jonahsnider\/frc\//' | tr '\n' ' ')
          echo "formulae=$formulae" >> "$GITHUB_OUTPUT"
      - name: Bump packages
        uses: Homebrew/actions/bump-packages@1e34f2e2acaa766b7efacb8c26352e6abbb023f9 # 2026.09.13.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          casks: ${{ steps.list-casks.outputs.casks }}
          formulae: ${{ steps.list-formulae.outputs.formulae }}
          fork: false
